id = "gleam"
name = "Gleam"
description = "Gleam support."
version = "0.5.1"
schema_version = 1
authors = ["Marshall Bowers <elliott.codes@gmail.com>"]
repository = "https://github.com/gleam-lang/zed-gleam"

[language_servers.gleam]
name = "Gleam LSP"
language = "Gleam"

[grammars.gleam]
repository = "https://github.com/gleam-lang/tree-sitter-gleam"
commit = "6ece453acf8b14568c10f629f8cd25d3dde3794f"

[slash_commands.gleam-project]
description = "Returns information about the current Gleam project."
requires_argument = false
