id = "gleam"
name = "Gleam"
description = "Gleam support."
version = "0.6.0"
schema_version = 1
authors = ["Marshall Bowers <elliott.codes@gmail.com>"]
repository = "https://github.com/gleam-lang/zed-gleam"
snippets = "snippets.json"

[language_servers.gleam]
name = "Gleam LSP"
language = "Gleam"

[grammars.gleam]
repository = "https://github.com/gleam-lang/tree-sitter-gleam"
commit = "6ea757f7eb8d391dbf24dbb9461990757946dd5e"

[slash_commands.gleam-project]
description = "Returns information about the current Gleam project."
requires_argument = false
